LANGUAGES = {
    'zh': {
        'title': "CAN协议上位机 - 创芯科技CANalyst-II",
        'connect': "连接",
        'disconnect': "断开",
        'start_send': "启动发送",
        'stop_send': "停止发送",
        'receive_control': "接收控制:",
        'open_receive': "开启接收",
        'send_control': "发送控制:",
        'status': "状态",
        'send': "发送",
        'receive': "接收",
        'heartbeat_status': "心跳状态",
        'stat_info': "统计信息",
        'send_data': "发送数据",
        'realtime_data': "实时数据",
        'log': "通信日志",
        'clear_log': "清空日志",
        'auto_save_log': "自动保存日志",
        'save_log': "保存日志",
        'language': "语言/Language:",
        'connection_settings': "连接设置",
        'control': "控制",
        'device_type': "设备类型:",
        'device_index': "设备索引:",
        'can_channel': "CAN通道:",
        'baud_rate': "波特率:",
        'can_id': "CAN ID",
        'parameter': "参数",
        'value': "数值",
        'unit': "单位",
        'status_col': "状态",
        'refresh_time': "刷新时间",
        'send_status': "发送状态",
        'send_count': "发送次数",
        'send_time': "发送时间",
        'stop_send': "停止发送",
        'start_send_status': "正在发送",
        'stopped': "已停止",
        'normal': "正常",
        'waiting': "等待",
        'stop': "停止",
        'yes': "是",
        'no': "否",
        # 表格项（仅示例，需补全所有项）
        'table_351': [
            ('心跳状态', 'heartbeat_status'),
            ('充电电压限制', 'charge_voltage_limit'),
            ('最大充电电流', 'max_charge_current'),
            ('最大放电电流', 'max_discharge_current'),
            ('放电电压', 'discharge_voltage'),
        ],
        'table_355': [
            ('SOC值', 'soc_value'),
            ('SOH值', 'soh_value'),
            ('高精度SOC', 'high_res_soc'),
        ],
        'table_356': [
            ('电池电压', 'battery_voltage'),
            ('电池电流', 'battery_current'),
            ('电池温度', 'battery_temperature'),
        ],
        'table_35A_alarm': [
            ('总报警', 'general_alarm'),
            ('电池高压报警', 'battery_high_voltage_alarm'),
            ('电池低压报警', 'battery_low_voltage_alarm'),
            ('电池高温报警', 'battery_high_temp_alarm'),
            ('电池低温报警', 'battery_low_temp_alarm'),
            ('电池高温充电报警', 'battery_high_temp_charge_alarm'),
            ('电池低温充电报警', 'battery_low_temp_charge_alarm'),
            ('电池高电流报警', 'battery_high_current_alarm'),
            ('电池高充电电流报警', 'battery_high_charge_current_alarm'),
            ('接触器报警', 'contactor_alarm'),
            ('短路报警', 'short_circuit_alarm'),
            ('BMS内部报警', 'bms_internal_alarm'),
            ('电池不平衡报警', 'cell_imbalance_alarm'),
        ],
        'table_35A_warning': [
            ('总警告', 'general_warning'),
            ('电池高压警告', 'battery_high_voltage'),
            ('电池低压警告', 'battery_low_voltage'),
            ('电池高温警告', 'battery_high_temp'),
            ('电池低温警告', 'battery_low_temp'),
            ('电池高温充电警告', 'battery_high_temp_charge'),
            ('电池低温充电警告', 'battery_low_temp_charge'),
            ('电池高电流警告', 'battery_high_current'),
            ('电池高充电电流警告', 'battery_high_charge_current'),
            ('接触器警告', 'contactor_warning'),
            ('短路警告', 'short_circuit_warning'),
            ('BMS内部警告', 'bms_internal'),
            ('电池不平衡警告', 'cell_imbalance'),
            ('系统状态', 'system_online'),
        ],
    },
    'en': {
        'title': "CAN Host Computer - CANalyst-II",
        'connect': "Connect",
        'disconnect': "Disconnect",
        'start_send': "Start Send",
        'stop_send': "Stop Send",
        'receive_control': "Receive Control:",
        'open_receive': "Enable Receive",
        'send_control': "Send Control:",
        'status': "Status",
        'send': "Send",
        'receive': "Receive",
        'heartbeat_status': "Heartbeat",
        'stat_info': "Statistics",
        'send_data': "Send Data",
        'realtime_data': "Realtime Data",
        'log': "Communication Log",
        'clear_log': "Clear Log",
        'auto_save_log': "Auto Save Log",
        'save_log': "Save Log",
        'language': "Language:",
        'connection_settings': "Connection Settings",
        'control': "Control",
        'device_type': "Device Type:",
        'device_index': "Device Index:",
        'can_channel': "CAN Channel:",
        'baud_rate': "Baud Rate:",
        'can_id': "CAN ID",
        'parameter': "Parameter",
        'value': "Value",
        'unit': "Unit",
        'status_col': "Status",
        'refresh_time': "Refresh Time",
        'send_status': "Send Status",
        'send_count': "Send Count",
        'send_time': "Send Time",
        'stop_send': "Stop Send",
        'start_send_status': "Sending",
        'stopped': "Stopped",
        'normal': "Normal",
        'waiting': "Waiting",
        'stop': "Stop",
        'yes': "Yes",
        'no': "No",
        # 表格项（仅示例，需补全所有项）
        'table_351': [
            ('Heartbeat', 'heartbeat_status'),
            ('Charge Voltage Limit', 'charge_voltage_limit'),
            ('Max Charge Current', 'max_charge_current'),
            ('Max Discharge Current', 'max_discharge_current'),
            ('Discharge Voltage', 'discharge_voltage'),
        ],
        'table_355': [
            ('SOC Value', 'soc_value'),
            ('SOH Value', 'soh_value'),
            ('High Precision SOC', 'high_res_soc'),
        ],
        'table_356': [  
            ('Battery Voltage', 'battery_voltage'), 
            ('Battery Current', 'battery_current'),
            ('Battery Temperature', 'battery_temperature'),
        ],
        'table_35A_alarm': [
            ('General Alarm', 'general_alarm'),
            ('Battery High Voltage Alarm', 'battery_high_voltage_alarm'),
            ('Battery Low Voltage Alarm', 'battery_low_voltage_alarm'),
            ('Battery High Temp Alarm', 'battery_high_temp_alarm'),
            ('Battery Low Temp Alarm', 'battery_low_temp_alarm'),
            ('Battery High Temp Charge Alarm', 'battery_high_temp_charge_alarm'),
            ('Battery Low Temp Charge Alarm', 'battery_low_temp_charge_alarm'),
            ('Battery High Current Alarm', 'battery_high_current_alarm'),
            ('Battery High Charge Current Alarm', 'battery_high_charge_current_alarm'),
            ('Contactor Alarm', 'contactor_alarm'),
            ('Short Circuit Alarm', 'short_circuit_alarm'),
            ('BMS Internal Alarm', 'bms_internal_alarm'),
            ('Cell Imbalance Alarm', 'cell_imbalance_alarm'),
        ],
        'table_35A_warning': [
            ('General Warning', 'general_warning'),
            ('Battery High Voltage Warning', 'battery_high_voltage'),
            ('Battery Low Voltage Warning', 'battery_low_voltage'),
            ('Battery High Temp Warning', 'battery_high_temp'),
            ('Battery Low Temp Warning', 'battery_low_temp'),
            ('Battery High Temp Charge Warning', 'battery_high_temp_charge'),
            ('Battery Low Temp Charge Warning', 'battery_low_temp_charge'),
            ('Battery High Current Warning', 'battery_high_current'),
            ('Battery High Charge Current Warning', 'battery_high_charge_current'),
            ('Contactor Warning', 'contactor_warning'),
            ('Short Circuit Warning', 'short_circuit_warning'),
            ('BMS Internal Warning', 'bms_internal'),
            ('Cell Imbalance Warning', 'cell_imbalance'),
            ('System Status', 'system_online'),
        ],
    }
} 